import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LoginBtn from "./components/LoginBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // 로그인 여부 확인 (비어있으면 로그인안됨)
  let session = await getServerSession(authOptions);
  console.log(session)

  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="">
          <Link href="/">게시글</Link>
          <Link href="/write">글쓰기</Link>
          {/* 로그인/회원가입, 로그아웃/이름 : 구글로그인, 깃허브로그인, 자체DB로그인 */}
          <LoginBtn login={session}></LoginBtn>
        </nav>
        {children}
      </body>
    </html>
  );
}
